
module.exports = {
    LOAD_ARTICLES: 'LOAD_ARTICLES',
    LOAD_SINGLE_ARTICLE: 'LOAD_SINGLE_ARTICLE',
    CREATE_ARTICLE: 'CREATE_ARTICLE',
    CREATE_ARTICLE_SUCCESSFUL: 'CREATE_ARTICLE_SUCCESSFUL',
    CREATE_ARTICLE_FAILED: 'CREATE_ARTICLE_FAILED'
};
